export interface StoreTemplate {
  id: string;
  name: string;
  description: string;
  preview: string;
  category: string;
  defaultSections: any[];
  styleSettings: Record<string, any>;
}

export const TEMPLATE_CATEGORIES = [
  'all', 'dark', 'light', 'colorful', 'minimal', 'gaming', 'luxury', 'creative', 'retro', 'nature', 'tech'
];

export const STORE_TEMPLATES: StoreTemplate[] = [
  // 1. Dark Violet
  {
    id: 'dark-violet',
    name: 'Dark Violet',
    category: 'dark',
    description: 'Sleek dark theme with violet accents',
    preview: 'linear-gradient(135deg, #0a0a0a 0%, #7c3aed 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Unleash the Dark Side', subheading: 'Premium products with a bold edge', showButton: true, buttonText: 'Shop Now' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'testimonials', type: 'testimonials', order: 3, settings: { title: 'What Customers Say', testimonials: [{ name: 'Alex', text: 'Amazing products!', rating: 5 }, { name: 'Sam', text: 'Great quality.', rating: 5 }, { name: 'Jordan', text: 'Highly recommend!', rating: 5 }] } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'dark-violet',
      page_bg_color: '#0a0a0a',
      card_bg_color: '#111111',
      text_color: '#ffffff',
      primary_button_bg: '#7c3aed',
      primary_button_text: '#ffffff',
      primary_button_border: '#7c3aed',
      primary_button_bg_hover: '#6d28d9',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#6d28d9',
      background_type: 'solid',
      font_family: 'Inter',
      heading_font: 'Inter',
      button_style: 'rounded',
      card_style: 'standard',
    },
  },

  // 2. Midnight Blue
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    category: 'dark',
    description: 'Deep blue gradient with clean typography',
    preview: 'linear-gradient(135deg, #0f172a 0%, #1e3a8a 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Into the Deep Blue', subheading: 'Discover products that stand out', showButton: true, buttonText: 'Shop Now' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'newsletter', type: 'newsletter', order: 3, heading: 'Stay Updated', description: 'Get the latest drops.' },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'midnight-blue',
      page_bg_color: '#0f172a',
      card_bg_color: '#1e293b',
      text_color: '#f1f5f9',
      primary_button_bg: '#3b82f6',
      primary_button_text: '#ffffff',
      primary_button_border: '#3b82f6',
      primary_button_bg_hover: '#2563eb',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#2563eb',
      background_type: 'gradient',
      gradient_start: '#0f172a',
      gradient_end: '#1e3a8a',
      font_family: 'Inter',
      heading_font: 'Inter',
      button_style: 'rounded',
      card_style: 'standard',
    },
  },

  // 3. Minimal Light
  {
    id: 'minimal-light',
    name: 'Minimal Light',
    category: 'minimal',
    description: 'Clean white layout for a professional look',
    preview: 'linear-gradient(135deg, #ffffff 0%, #f3f4f6 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Simply Beautiful', subheading: 'Curated products for the discerning buyer', showButton: true, buttonText: 'Shop Now' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'minimal' } },
      { id: 'footer', type: 'footer', order: 3, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'minimal-light',
      page_bg_color: '#ffffff',
      card_bg_color: '#f9fafb',
      text_color: '#111827',
      primary_button_bg: '#111827',
      primary_button_text: '#ffffff',
      primary_button_border: '#111827',
      primary_button_bg_hover: '#374151',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#374151',
      background_type: 'solid',
      font_family: 'Inter',
      heading_font: 'Inter',
      button_style: 'square',
      card_style: 'minimal',
    },
  },

  // 4. Neon Green
  {
    id: 'neon-green',
    name: 'Neon Green',
    category: 'gaming',
    description: 'Bold dark theme with neon green highlights',
    preview: 'linear-gradient(135deg, #0a0a0a 0%, #16a34a 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Level Up Your Game', subheading: 'Next-gen products for next-gen players', showButton: true, buttonText: 'Shop Now' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'gaming' } },
      { id: 'footer', type: 'footer', order: 3, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'neon-green',
      page_bg_color: '#0a0a0a',
      card_bg_color: '#0d1117',
      text_color: '#ffffff',
      primary_button_bg: '#16a34a',
      primary_button_text: '#ffffff',
      primary_button_border: '#16a34a',
      primary_button_bg_hover: '#15803d',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#15803d',
      background_type: 'solid',
      font_family: 'Inter',
      heading_font: 'Inter',
      button_style: 'rounded',
      card_style: 'gaming',
    },
  },

  // 5. Crimson
  {
    id: 'crimson',
    name: 'Crimson',
    category: 'dark',
    description: 'Bold red accents on a dark canvas',
    preview: 'linear-gradient(135deg, #0a0a0a 0%, #dc2626 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Bold. Fierce. Unstoppable.', subheading: 'Products that make a statement', showButton: true, buttonText: 'Shop Now' } },
      { id: 'featured', type: 'featured_products', order: 2, settings: { title: 'Featured' } },
      { id: 'products', type: 'product_grid', order: 3, settings: { title: 'All Products', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'crimson',
      page_bg_color: '#0a0a0a',
      card_bg_color: '#111111',
      text_color: '#ffffff',
      primary_button_bg: '#dc2626',
      primary_button_text: '#ffffff',
      primary_button_border: '#dc2626',
      primary_button_bg_hover: '#b91c1c',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#b91c1c',
      background_type: 'solid',
      font_family: 'Inter',
      heading_font: 'Inter',
      button_style: 'rounded',
      card_style: 'standard',
    },
  },

  // 6. Forest
  {
    id: 'forest',
    name: 'Forest',
    category: 'nature',
    description: 'Earthy tones with a natural feel',
    preview: 'linear-gradient(135deg, #1a2e1a 0%, #4d7c0f 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Back to Nature', subheading: 'Organic, earthy, and beautifully crafted', showButton: true, buttonText: 'Explore' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Our Collection', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'testimonials', type: 'testimonials', order: 3, settings: { title: 'What Customers Say', testimonials: [{ name: 'Alex', text: 'Amazing products!', rating: 5 }, { name: 'Sam', text: 'Great quality.', rating: 5 }, { name: 'Jordan', text: 'Highly recommend!', rating: 5 }] } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'forest',
      page_bg_color: '#1a2e1a',
      card_bg_color: '#1f3a1f',
      text_color: '#f0fdf4',
      primary_button_bg: '#4d7c0f',
      primary_button_text: '#ffffff',
      primary_button_border: '#4d7c0f',
      primary_button_bg_hover: '#3f6212',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#3f6212',
      background_type: 'solid',
      font_family: 'Poppins',
      heading_font: 'Poppins',
      button_style: 'rounded',
      card_style: 'standard',
    },
  },

  // 7. Rose Gold
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    category: 'luxury',
    description: 'Elegant rose gold luxury aesthetic',
    preview: 'linear-gradient(135deg, #1a0a0a 0%, #c2856a 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Timeless Elegance', subheading: 'Luxury crafted for the modern connoisseur', showButton: true, buttonText: 'Discover' } },
      { id: 'featured', type: 'featured_products', order: 2, settings: { title: 'Featured Pieces' } },
      { id: 'products', type: 'product_grid', order: 3, settings: { title: 'The Collection', productsPerRow: '4', cardStyle: 'elevated' } },
      { id: 'newsletter', type: 'newsletter', order: 4, heading: 'Join the Inner Circle', description: 'Exclusive access to new arrivals and private sales.' },
      { id: 'footer', type: 'footer', order: 5, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'rose-gold',
      page_bg_color: '#1a0a0a',
      card_bg_color: '#2a1515',
      text_color: '#fde8e0',
      primary_button_bg: '#c2856a',
      primary_button_text: '#ffffff',
      primary_button_border: '#c2856a',
      primary_button_bg_hover: '#a86b52',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#a86b52',
      background_type: 'solid',
      font_family: 'Playfair Display',
      heading_font: 'Playfair Display',
      button_style: 'pill',
      card_style: 'elevated',
    },
  },

  // 8. Cyberpunk
  {
    id: 'cyber-punk',
    name: 'Cyberpunk',
    category: 'gaming',
    description: 'Neon yellow on pitch black — pure cyber energy',
    preview: 'linear-gradient(135deg, #000000 0%, #facc15 50%, #f97316 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'WELCOME TO THE FUTURE', subheading: 'High-tech products for a high-tech world', showButton: true, buttonText: 'JACK IN' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'INVENTORY', productsPerRow: '4', cardStyle: 'gaming' } },
      { id: 'footer', type: 'footer', order: 3, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'cyber-punk',
      page_bg_color: '#000000',
      card_bg_color: '#0a0a00',
      text_color: '#facc15',
      primary_button_bg: '#facc15',
      primary_button_text: '#000000',
      primary_button_border: '#facc15',
      primary_button_bg_hover: '#eab308',
      primary_button_text_hover: '#000000',
      primary_button_border_hover: '#eab308',
      background_type: 'solid',
      font_family: 'Inter',
      heading_font: 'Inter',
      button_style: 'square',
      card_style: 'gaming',
    },
  },

  // 9. Ocean Breeze
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    category: 'colorful',
    description: 'Fresh teal and ocean blue vibes',
    preview: 'linear-gradient(135deg, #0c4a6e 0%, #06b6d4 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Ride the Wave', subheading: 'Fresh finds from the deep blue', showButton: true, buttonText: 'Dive In' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'hover-reveal' } },
      { id: 'testimonials', type: 'testimonials', order: 3, settings: { title: 'What Customers Say', testimonials: [{ name: 'Alex', text: 'Amazing products!', rating: 5 }, { name: 'Sam', text: 'Great quality.', rating: 5 }, { name: 'Jordan', text: 'Highly recommend!', rating: 5 }] } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'ocean-breeze',
      page_bg_color: '#0c4a6e',
      card_bg_color: '#0e5a80',
      text_color: '#e0f7fa',
      primary_button_bg: '#06b6d4',
      primary_button_text: '#ffffff',
      primary_button_border: '#06b6d4',
      primary_button_bg_hover: '#0891b2',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#0891b2',
      background_type: 'gradient',
      gradient_start: '#0c4a6e',
      gradient_end: '#164e63',
      font_family: 'Poppins',
      heading_font: 'Poppins',
      button_style: 'rounded',
      card_style: 'hover-reveal',
    },
  },

  // 10. Sunset
  {
    id: 'sunset',
    name: 'Sunset',
    category: 'colorful',
    description: 'Warm orange-to-pink sunset gradient',
    preview: 'linear-gradient(135deg, #7c2d12 0%, #ea580c 50%, #db2777 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Golden Hour Finds', subheading: 'Warm, vibrant, and full of life', showButton: true, buttonText: 'Shop Now' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'newsletter', type: 'newsletter', order: 3, heading: 'Catch the Latest Drop', description: 'Get the latest drops.' },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'sunset',
      page_bg_color: '#1a0a00',
      card_bg_color: '#2a1500',
      text_color: '#fff7ed',
      primary_button_bg: '#ea580c',
      primary_button_text: '#ffffff',
      primary_button_border: '#ea580c',
      primary_button_bg_hover: '#c2410c',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#c2410c',
      background_type: 'gradient',
      gradient_start: '#7c2d12',
      gradient_end: '#9d174d',
      font_family: 'Poppins',
      heading_font: 'Poppins',
      button_style: 'rounded',
      card_style: 'standard',
    },
  },

  // 11. Arctic
  {
    id: 'arctic',
    name: 'Arctic',
    category: 'minimal',
    description: 'Ice-cold white and pale blue minimalism',
    preview: 'linear-gradient(135deg, #f0f9ff 0%, #bae6fd 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Cool. Calm. Collected.', subheading: 'Crisp products for a clear mind', showButton: true, buttonText: 'Shop Now' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'minimal' } },
      { id: 'footer', type: 'footer', order: 3, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'arctic',
      page_bg_color: '#f0f9ff',
      card_bg_color: '#ffffff',
      text_color: '#0c4a6e',
      primary_button_bg: '#0284c7',
      primary_button_text: '#ffffff',
      primary_button_border: '#0284c7',
      primary_button_bg_hover: '#0369a1',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#0369a1',
      background_type: 'solid',
      font_family: 'Inter',
      heading_font: 'Inter',
      button_style: 'rounded',
      card_style: 'minimal',
    },
  },

  // 12. Obsidian
  {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'dark',
    description: 'Pure black with silver chrome accents',
    preview: 'linear-gradient(135deg, #000000 0%, #374151 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Forged in Darkness', subheading: 'Premium quality, uncompromising style', showButton: true, buttonText: 'Shop Now' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'testimonials', type: 'testimonials', order: 3, settings: { title: 'What Customers Say', testimonials: [{ name: 'Alex', text: 'Amazing products!', rating: 5 }, { name: 'Sam', text: 'Great quality.', rating: 5 }, { name: 'Jordan', text: 'Highly recommend!', rating: 5 }] } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'obsidian',
      page_bg_color: '#000000',
      card_bg_color: '#0a0a0a',
      text_color: '#e5e7eb',
      primary_button_bg: '#6b7280',
      primary_button_text: '#ffffff',
      primary_button_border: '#6b7280',
      primary_button_bg_hover: '#9ca3af',
      primary_button_text_hover: '#000000',
      primary_button_border_hover: '#9ca3af',
      background_type: 'solid',
      font_family: 'Montserrat',
      heading_font: 'Montserrat',
      button_style: 'square',
      card_style: 'standard',
    },
  },

  // 13. Sakura
  {
    id: 'sakura',
    name: 'Sakura',
    category: 'light',
    description: 'Soft pink Japanese cherry blossom aesthetic',
    preview: 'linear-gradient(135deg, #fff1f2 0%, #fda4af 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'In Full Bloom', subheading: 'Delicate beauty in every product', showButton: true, buttonText: 'Explore' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'The Collection', productsPerRow: '4', cardStyle: 'elevated' } },
      { id: 'testimonials', type: 'testimonials', order: 3, settings: { title: 'What Customers Say', testimonials: [{ name: 'Alex', text: 'Amazing products!', rating: 5 }, { name: 'Sam', text: 'Great quality.', rating: 5 }, { name: 'Jordan', text: 'Highly recommend!', rating: 5 }] } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'sakura',
      page_bg_color: '#fff1f2',
      card_bg_color: '#ffffff',
      text_color: '#881337',
      primary_button_bg: '#f43f5e',
      primary_button_text: '#ffffff',
      primary_button_border: '#f43f5e',
      primary_button_bg_hover: '#e11d48',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#e11d48',
      background_type: 'solid',
      font_family: 'Poppins',
      heading_font: 'Playfair Display',
      button_style: 'pill',
      card_style: 'elevated',
    },
  },

  // 14. Matrix
  {
    id: 'matrix',
    name: 'Matrix',
    category: 'gaming',
    description: 'Green on black terminal hacker aesthetic',
    preview: 'linear-gradient(135deg, #000000 0%, #052e16 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'ENTER THE MATRIX', subheading: 'There is no spoon — only great products', showButton: true, buttonText: 'INITIALIZE' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: '> CATALOG', productsPerRow: '4', cardStyle: 'gaming' } },
      { id: 'footer', type: 'footer', order: 3, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'matrix',
      page_bg_color: '#000000',
      card_bg_color: '#0a0f0a',
      text_color: '#4ade80',
      primary_button_bg: '#16a34a',
      primary_button_text: '#000000',
      primary_button_border: '#16a34a',
      primary_button_bg_hover: '#4ade80',
      primary_button_text_hover: '#000000',
      primary_button_border_hover: '#4ade80',
      background_type: 'solid',
      font_family: 'Roboto Mono',
      heading_font: 'Roboto Mono',
      button_style: 'square',
      card_style: 'gaming',
    },
  },

  // 15. Lavender Dream
  {
    id: 'lavender-dream',
    name: 'Lavender Dream',
    category: 'light',
    description: 'Soft purple pastel with dreamy vibes',
    preview: 'linear-gradient(135deg, #faf5ff 0%, #d8b4fe 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Dream in Color', subheading: 'Soft, sweet, and wonderfully curated', showButton: true, buttonText: 'Shop Now' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'elevated' } },
      { id: 'newsletter', type: 'newsletter', order: 3, heading: 'Stay in the Dream', description: 'Get the latest drops.' },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'lavender-dream',
      page_bg_color: '#faf5ff',
      card_bg_color: '#f3e8ff',
      text_color: '#4c1d95',
      primary_button_bg: '#9333ea',
      primary_button_text: '#ffffff',
      primary_button_border: '#9333ea',
      primary_button_bg_hover: '#7e22ce',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#7e22ce',
      background_type: 'solid',
      font_family: 'Poppins',
      heading_font: 'Poppins',
      button_style: 'pill',
      card_style: 'elevated',
    },
  },

  // 16. Gold Rush
  {
    id: 'gold-rush',
    name: 'Gold Rush',
    category: 'luxury',
    description: 'Deep black with premium gold accents',
    preview: 'linear-gradient(135deg, #0a0800 0%, #d97706 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Pure Gold', subheading: 'Where luxury meets craftsmanship', showButton: true, buttonText: 'Discover' } },
      { id: 'featured', type: 'featured_products', order: 2, settings: { title: 'Signature Pieces' } },
      { id: 'products', type: 'product_grid', order: 3, settings: { title: 'The Vault', productsPerRow: '4', cardStyle: 'elevated' } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'gold-rush',
      page_bg_color: '#0a0800',
      card_bg_color: '#1a1400',
      text_color: '#fef3c7',
      primary_button_bg: '#d97706',
      primary_button_text: '#000000',
      primary_button_border: '#d97706',
      primary_button_bg_hover: '#f59e0b',
      primary_button_text_hover: '#000000',
      primary_button_border_hover: '#f59e0b',
      background_type: 'solid',
      font_family: 'Playfair Display',
      heading_font: 'Playfair Display',
      button_style: 'pill',
      card_style: 'elevated',
    },
  },

  // 17. Retro Wave
  {
    id: 'retro-wave',
    name: 'Retro Wave',
    category: 'retro',
    description: '80s synthwave purple and pink neon',
    preview: 'linear-gradient(135deg, #1a0533 0%, #7c3aed 50%, #ec4899 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'DRIVE INTO THE NIGHT', subheading: 'Synthwave aesthetics for the modern era', showButton: true, buttonText: 'RIDE' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'testimonials', type: 'testimonials', order: 3, settings: { title: 'What Customers Say', testimonials: [{ name: 'Alex', text: 'Amazing products!', rating: 5 }, { name: 'Sam', text: 'Great quality.', rating: 5 }, { name: 'Jordan', text: 'Highly recommend!', rating: 5 }] } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'retro-wave',
      page_bg_color: '#1a0533',
      card_bg_color: '#2d0a4e',
      text_color: '#f0abfc',
      primary_button_bg: '#ec4899',
      primary_button_text: '#ffffff',
      primary_button_border: '#ec4899',
      primary_button_bg_hover: '#db2777',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#db2777',
      background_type: 'gradient',
      gradient_start: '#1a0533',
      gradient_end: '#4a044e',
      font_family: 'Montserrat',
      heading_font: 'Montserrat',
      button_style: 'rounded',
      card_style: 'standard',
    },
  },

  // 18. Sand Dune
  {
    id: 'sand-dune',
    name: 'Sand Dune',
    category: 'nature',
    description: 'Warm sandy beige desert aesthetic',
    preview: 'linear-gradient(135deg, #fef3c7 0%, #d97706 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Desert Crafted', subheading: 'Warm tones, timeless quality', showButton: true, buttonText: 'Explore' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Our Wares', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'testimonials', type: 'testimonials', order: 3, settings: { title: 'What Customers Say', testimonials: [{ name: 'Alex', text: 'Amazing products!', rating: 5 }, { name: 'Sam', text: 'Great quality.', rating: 5 }, { name: 'Jordan', text: 'Highly recommend!', rating: 5 }] } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'sand-dune',
      page_bg_color: '#fef9ee',
      card_bg_color: '#fffbf0',
      text_color: '#78350f',
      primary_button_bg: '#d97706',
      primary_button_text: '#ffffff',
      primary_button_border: '#d97706',
      primary_button_bg_hover: '#b45309',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#b45309',
      background_type: 'solid',
      font_family: 'Poppins',
      heading_font: 'Playfair Display',
      button_style: 'rounded',
      card_style: 'standard',
    },
  },

  // 19. Deep Space
  {
    id: 'deep-space',
    name: 'Deep Space',
    category: 'dark',
    description: 'Cosmic dark with nebula purple and star white',
    preview: 'linear-gradient(135deg, #020617 0%, #4c1d95 50%, #1e1b4b 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Beyond the Stars', subheading: 'Products from another dimension', showButton: true, buttonText: 'Launch' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'newsletter', type: 'newsletter', order: 3, heading: 'Mission Briefing', description: 'Get the latest drops.' },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'deep-space',
      page_bg_color: '#020617',
      card_bg_color: '#0f0a1e',
      text_color: '#e2e8f0',
      primary_button_bg: '#8b5cf6',
      primary_button_text: '#ffffff',
      primary_button_border: '#8b5cf6',
      primary_button_bg_hover: '#7c3aed',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#7c3aed',
      background_type: 'gradient',
      gradient_start: '#020617',
      gradient_end: '#1e1b4b',
      font_family: 'Inter',
      heading_font: 'Inter',
      button_style: 'rounded',
      card_style: 'standard',
    },
  },

  // 20. Coral Reef
  {
    id: 'coral-reef',
    name: 'Coral Reef',
    category: 'colorful',
    description: 'Vibrant coral and turquoise tropical energy',
    preview: 'linear-gradient(135deg, #ff6b6b 0%, #4ecdc4 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Tropical Vibes Only', subheading: 'Bright, bold, and full of energy', showButton: true, buttonText: 'Dive In' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'hover-reveal' } },
      { id: 'testimonials', type: 'testimonials', order: 3, settings: { title: 'What Customers Say', testimonials: [{ name: 'Alex', text: 'Amazing products!', rating: 5 }, { name: 'Sam', text: 'Great quality.', rating: 5 }, { name: 'Jordan', text: 'Highly recommend!', rating: 5 }] } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'coral-reef',
      page_bg_color: '#fff5f5',
      card_bg_color: '#ffffff',
      text_color: '#1a1a2e',
      primary_button_bg: '#ff6b6b',
      primary_button_text: '#ffffff',
      primary_button_border: '#ff6b6b',
      primary_button_bg_hover: '#ee5a5a',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#ee5a5a',
      background_type: 'solid',
      font_family: 'Poppins',
      heading_font: 'Poppins',
      button_style: 'pill',
      card_style: 'hover-reveal',
    },
  },

  // 21. Monochrome
  {
    id: 'monochrome',
    name: 'Monochrome',
    category: 'minimal',
    description: 'Pure black and white editorial style',
    preview: 'linear-gradient(135deg, #000000 0%, #ffffff 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Black. White. Perfect.', subheading: 'Editorial minimalism at its finest', showButton: true, buttonText: 'Shop Now' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'minimal' } },
      { id: 'footer', type: 'footer', order: 3, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'monochrome',
      page_bg_color: '#ffffff',
      card_bg_color: '#f5f5f5',
      text_color: '#000000',
      primary_button_bg: '#000000',
      primary_button_text: '#ffffff',
      primary_button_border: '#000000',
      primary_button_bg_hover: '#333333',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#333333',
      background_type: 'solid',
      font_family: 'Montserrat',
      heading_font: 'Montserrat',
      button_style: 'square',
      card_style: 'minimal',
    },
  },

  // 22. Electric Blue
  {
    id: 'electric-blue',
    name: 'Electric Blue',
    category: 'tech',
    description: 'High-voltage electric blue on dark',
    preview: 'linear-gradient(135deg, #000814 0%, #0077b6 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Power Up', subheading: 'High-performance products for high-performance people', showButton: true, buttonText: 'Get Started' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'newsletter', type: 'newsletter', order: 3, heading: 'Stay Charged', description: 'Get the latest drops.' },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'electric-blue',
      page_bg_color: '#000814',
      card_bg_color: '#001d3d',
      text_color: '#caf0f8',
      primary_button_bg: '#0077b6',
      primary_button_text: '#ffffff',
      primary_button_border: '#0077b6',
      primary_button_bg_hover: '#0096c7',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#0096c7',
      background_type: 'solid',
      font_family: 'Roboto',
      heading_font: 'Roboto',
      button_style: 'rounded',
      card_style: 'standard',
    },
  },

  // 23. Emerald City
  {
    id: 'emerald-city',
    name: 'Emerald City',
    category: 'nature',
    description: 'Rich emerald green luxury',
    preview: 'linear-gradient(135deg, #022c22 0%, #059669 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'The Emerald Standard', subheading: 'Lush, rich, and undeniably premium', showButton: true, buttonText: 'Explore' } },
      { id: 'featured', type: 'featured_products', order: 2, settings: { title: 'Featured' } },
      { id: 'products', type: 'product_grid', order: 3, settings: { title: 'All Products', productsPerRow: '4', cardStyle: 'elevated' } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'emerald-city',
      page_bg_color: '#022c22',
      card_bg_color: '#064e3b',
      text_color: '#d1fae5',
      primary_button_bg: '#059669',
      primary_button_text: '#ffffff',
      primary_button_border: '#059669',
      primary_button_bg_hover: '#047857',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#047857',
      background_type: 'solid',
      font_family: 'Poppins',
      heading_font: 'Poppins',
      button_style: 'rounded',
      card_style: 'elevated',
    },
  },

  // 24. Bubblegum
  {
    id: 'bubblegum',
    name: 'Bubblegum',
    category: 'colorful',
    description: 'Fun pink and purple candy pop aesthetic',
    preview: 'linear-gradient(135deg, #fdf2f8 0%, #f0abfc 50%, #a78bfa 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Sweet & Playful', subheading: 'Life is too short for boring products', showButton: true, buttonText: 'Let\'s Go!' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'hover-reveal' } },
      { id: 'testimonials', type: 'testimonials', order: 3, settings: { title: 'What Customers Say', testimonials: [{ name: 'Alex', text: 'Amazing products!', rating: 5 }, { name: 'Sam', text: 'Great quality.', rating: 5 }, { name: 'Jordan', text: 'Highly recommend!', rating: 5 }] } },
      { id: 'newsletter', type: 'newsletter', order: 4, heading: 'Get the Sweetest Deals', description: 'Get the latest drops.' },
      { id: 'footer', type: 'footer', order: 5, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'bubblegum',
      page_bg_color: '#fdf2f8',
      card_bg_color: '#fce7f3',
      text_color: '#701a75',
      primary_button_bg: '#d946ef',
      primary_button_text: '#ffffff',
      primary_button_border: '#d946ef',
      primary_button_bg_hover: '#c026d3',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#c026d3',
      background_type: 'solid',
      font_family: 'Poppins',
      heading_font: 'Poppins',
      button_style: 'pill',
      card_style: 'hover-reveal',
    },
  },

  // 25. Slate Pro
  {
    id: 'slate-pro',
    name: 'Slate Pro',
    category: 'tech',
    description: 'Professional slate grey SaaS-style layout',
    preview: 'linear-gradient(135deg, #0f172a 0%, #334155 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Built for Professionals', subheading: 'Tools and products that mean business', showButton: true, buttonText: 'Get Started' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'testimonials', type: 'testimonials', order: 3, settings: { title: 'What Customers Say', testimonials: [{ name: 'Alex', text: 'Amazing products!', rating: 5 }, { name: 'Sam', text: 'Great quality.', rating: 5 }, { name: 'Jordan', text: 'Highly recommend!', rating: 5 }] } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'slate-pro',
      page_bg_color: '#0f172a',
      card_bg_color: '#1e293b',
      text_color: '#cbd5e1',
      primary_button_bg: '#6366f1',
      primary_button_text: '#ffffff',
      primary_button_border: '#6366f1',
      primary_button_bg_hover: '#4f46e5',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#4f46e5',
      background_type: 'solid',
      font_family: 'Inter',
      heading_font: 'Inter',
      button_style: 'rounded',
      card_style: 'standard',
    },
  },

  // 26. Vintage Paper
  {
    id: 'vintage-paper',
    name: 'Vintage Paper',
    category: 'retro',
    description: 'Aged paper texture with sepia tones',
    preview: 'linear-gradient(135deg, #fdf6e3 0%, #c8a96e 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Est. Timeless', subheading: 'Crafted with care, built to last', showButton: true, buttonText: 'Browse' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Our Goods', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'testimonials', type: 'testimonials', order: 3, settings: { title: 'What Customers Say', testimonials: [{ name: 'Alex', text: 'Amazing products!', rating: 5 }, { name: 'Sam', text: 'Great quality.', rating: 5 }, { name: 'Jordan', text: 'Highly recommend!', rating: 5 }] } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'vintage-paper',
      page_bg_color: '#fdf6e3',
      card_bg_color: '#fef9ee',
      text_color: '#5c4a1e',
      primary_button_bg: '#8b6914',
      primary_button_text: '#ffffff',
      primary_button_border: '#8b6914',
      primary_button_bg_hover: '#6b5010',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#6b5010',
      background_type: 'solid',
      font_family: 'Playfair Display',
      heading_font: 'Playfair Display',
      button_style: 'rounded',
      card_style: 'standard',
    },
  },

  // 27. Neon Pink
  {
    id: 'neon-pink',
    name: 'Neon Pink',
    category: 'gaming',
    description: 'Hot pink neon on black — maximum energy',
    preview: 'linear-gradient(135deg, #000000 0%, #ec4899 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'MAXIMUM OVERDRIVE', subheading: 'Turn it up to eleven', showButton: true, buttonText: 'GO' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'gaming' } },
      { id: 'footer', type: 'footer', order: 3, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'neon-pink',
      page_bg_color: '#000000',
      card_bg_color: '#0f0010',
      text_color: '#fce7f3',
      primary_button_bg: '#ec4899',
      primary_button_text: '#ffffff',
      primary_button_border: '#ec4899',
      primary_button_bg_hover: '#db2777',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#db2777',
      background_type: 'solid',
      font_family: 'Montserrat',
      heading_font: 'Montserrat',
      button_style: 'pill',
      card_style: 'gaming',
    },
  },

  // 28. Nordic
  {
    id: 'nordic',
    name: 'Nordic',
    category: 'minimal',
    description: 'Scandinavian clean white with warm grey',
    preview: 'linear-gradient(135deg, #fafafa 0%, #e5e7eb 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Less is More', subheading: 'Thoughtfully designed, beautifully simple', showButton: true, buttonText: 'Shop Now' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'minimal' } },
      { id: 'newsletter', type: 'newsletter', order: 3, heading: 'Stay in the Loop', description: 'Get the latest drops.' },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'nordic',
      page_bg_color: '#fafafa',
      card_bg_color: '#ffffff',
      text_color: '#374151',
      primary_button_bg: '#374151',
      primary_button_text: '#ffffff',
      primary_button_border: '#374151',
      primary_button_bg_hover: '#1f2937',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#1f2937',
      background_type: 'solid',
      font_family: 'Inter',
      heading_font: 'Inter',
      button_style: 'square',
      card_style: 'minimal',
    },
  },

  // 29. Toxic
  {
    id: 'toxic',
    name: 'Toxic',
    category: 'gaming',
    description: 'Acid green and black toxic gaming aesthetic',
    preview: 'linear-gradient(135deg, #000000 0%, #84cc16 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'WARNING: TOXIC', subheading: 'Dangerously good products', showButton: true, buttonText: 'ENTER' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'PRODUCTS', productsPerRow: '4', cardStyle: 'gaming' } },
      { id: 'footer', type: 'footer', order: 3, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'toxic',
      page_bg_color: '#000000',
      card_bg_color: '#0a0f00',
      text_color: '#d9f99d',
      primary_button_bg: '#84cc16',
      primary_button_text: '#000000',
      primary_button_border: '#84cc16',
      primary_button_bg_hover: '#a3e635',
      primary_button_text_hover: '#000000',
      primary_button_border_hover: '#a3e635',
      background_type: 'solid',
      font_family: 'Roboto Mono',
      heading_font: 'Roboto Mono',
      button_style: 'square',
      card_style: 'gaming',
    },
  },

  // 30. Terracotta
  {
    id: 'terracotta',
    name: 'Terracotta',
    category: 'nature',
    description: 'Warm terracotta and clay earth tones',
    preview: 'linear-gradient(135deg, #fef2e8 0%, #c2410c 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Earth & Soul', subheading: 'Handcrafted with warmth and intention', showButton: true, buttonText: 'Discover' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Our Collection', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'testimonials', type: 'testimonials', order: 3, settings: { title: 'What Customers Say', testimonials: [{ name: 'Alex', text: 'Amazing products!', rating: 5 }, { name: 'Sam', text: 'Great quality.', rating: 5 }, { name: 'Jordan', text: 'Highly recommend!', rating: 5 }] } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'terracotta',
      page_bg_color: '#fef2e8',
      card_bg_color: '#fff7f0',
      text_color: '#7c2d12',
      primary_button_bg: '#c2410c',
      primary_button_text: '#ffffff',
      primary_button_border: '#c2410c',
      primary_button_bg_hover: '#9a3412',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#9a3412',
      background_type: 'solid',
      font_family: 'Poppins',
      heading_font: 'Playfair Display',
      button_style: 'rounded',
      card_style: 'standard',
    },
  },

  // 31. Ice Cream
  {
    id: 'ice-cream',
    name: 'Ice Cream',
    category: 'colorful',
    description: 'Pastel rainbow sorbet fun',
    preview: 'linear-gradient(135deg, #fce7f3 0%, #ddd6fe 50%, #bfdbfe 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Scoop of Happiness', subheading: 'Sweet products in every flavor', showButton: true, buttonText: 'Taste It' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'elevated' } },
      { id: 'newsletter', type: 'newsletter', order: 3, heading: 'New Flavors Dropping', description: 'Get the latest drops.' },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'ice-cream',
      page_bg_color: '#fdf4ff',
      card_bg_color: '#fce7f3',
      text_color: '#4c1d95',
      primary_button_bg: '#a855f7',
      primary_button_text: '#ffffff',
      primary_button_border: '#a855f7',
      primary_button_bg_hover: '#9333ea',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#9333ea',
      background_type: 'solid',
      font_family: 'Poppins',
      heading_font: 'Poppins',
      button_style: 'pill',
      card_style: 'elevated',
    },
  },

  // 32. Carbon Fiber
  {
    id: 'carbon-fiber',
    name: 'Carbon Fiber',
    category: 'tech',
    description: 'Dark carbon with orange tech accents',
    preview: 'linear-gradient(135deg, #111111 0%, #ea580c 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Engineered to Perform', subheading: 'Precision-crafted for those who demand more', showButton: true, buttonText: 'Shop Now' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'testimonials', type: 'testimonials', order: 3, settings: { title: 'What Customers Say', testimonials: [{ name: 'Alex', text: 'Amazing products!', rating: 5 }, { name: 'Sam', text: 'Great quality.', rating: 5 }, { name: 'Jordan', text: 'Highly recommend!', rating: 5 }] } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'carbon-fiber',
      page_bg_color: '#111111',
      card_bg_color: '#1a1a1a',
      text_color: '#f5f5f5',
      primary_button_bg: '#ea580c',
      primary_button_text: '#ffffff',
      primary_button_border: '#ea580c',
      primary_button_bg_hover: '#c2410c',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#c2410c',
      background_type: 'solid',
      font_family: 'Roboto',
      heading_font: 'Roboto',
      button_style: 'square',
      card_style: 'standard',
    },
  },

  // 33. Aurora
  {
    id: 'aurora',
    name: 'Aurora',
    category: 'colorful',
    description: 'Northern lights green and teal on dark',
    preview: 'linear-gradient(135deg, #022c22 0%, #065f46 50%, #0d9488 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Chase the Light', subheading: 'Rare finds that shimmer and shine', showButton: true, buttonText: 'Explore' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'hover-reveal' } },
      { id: 'newsletter', type: 'newsletter', order: 3, heading: 'Catch the Next Wave', description: 'Get the latest drops.' },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'aurora',
      page_bg_color: '#022c22',
      card_bg_color: '#064e3b',
      text_color: '#ccfbf1',
      primary_button_bg: '#0d9488',
      primary_button_text: '#ffffff',
      primary_button_border: '#0d9488',
      primary_button_bg_hover: '#0f766e',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#0f766e',
      background_type: 'gradient',
      gradient_start: '#022c22',
      gradient_end: '#134e4a',
      font_family: 'Inter',
      heading_font: 'Inter',
      button_style: 'rounded',
      card_style: 'hover-reveal',
    },
  },

  // 34. Royal Purple
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    category: 'luxury',
    description: 'Deep royal purple with gold trim',
    preview: 'linear-gradient(135deg, #1e0a3c 0%, #7c3aed 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Fit for Royalty', subheading: 'Regal products for distinguished tastes', showButton: true, buttonText: 'Enter' } },
      { id: 'featured', type: 'featured_products', order: 2, settings: { title: 'Crown Jewels' } },
      { id: 'products', type: 'product_grid', order: 3, settings: { title: 'The Royal Collection', productsPerRow: '4', cardStyle: 'elevated' } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'royal-purple',
      page_bg_color: '#1e0a3c',
      card_bg_color: '#2d1458',
      text_color: '#ede9fe',
      primary_button_bg: '#7c3aed',
      primary_button_text: '#ffffff',
      primary_button_border: '#7c3aed',
      primary_button_bg_hover: '#6d28d9',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#6d28d9',
      background_type: 'solid',
      font_family: 'Playfair Display',
      heading_font: 'Playfair Display',
      button_style: 'pill',
      card_style: 'elevated',
    },
  },

  // 35. Fire
  {
    id: 'fire',
    name: 'Fire',
    category: 'colorful',
    description: 'Blazing red-orange fire gradient',
    preview: 'linear-gradient(135deg, #1c0000 0%, #dc2626 50%, #f97316 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Set It Ablaze', subheading: 'Products that ignite your passion', showButton: true, buttonText: 'Ignite' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'footer', type: 'footer', order: 3, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'fire',
      page_bg_color: '#1c0000',
      card_bg_color: '#2a0000',
      text_color: '#fff7ed',
      primary_button_bg: '#dc2626',
      primary_button_text: '#ffffff',
      primary_button_border: '#dc2626',
      primary_button_bg_hover: '#b91c1c',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#b91c1c',
      background_type: 'gradient',
      gradient_start: '#1c0000',
      gradient_end: '#7c2d12',
      font_family: 'Montserrat',
      heading_font: 'Montserrat',
      button_style: 'rounded',
      card_style: 'standard',
    },
  },

  // 36. Zen
  {
    id: 'zen',
    name: 'Zen',
    category: 'minimal',
    description: 'Ultra-minimal white space Japanese zen',
    preview: 'linear-gradient(135deg, #ffffff 0%, #f9fafb 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'products', type: 'product_grid', order: 1, settings: { title: '', productsPerRow: '4', cardStyle: 'minimal' } },
      { id: 'footer', type: 'footer', order: 2, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'zen',
      page_bg_color: '#ffffff',
      card_bg_color: '#ffffff',
      text_color: '#374151',
      primary_button_bg: '#374151',
      primary_button_text: '#ffffff',
      primary_button_border: '#374151',
      primary_button_bg_hover: '#1f2937',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#1f2937',
      background_type: 'solid',
      font_family: 'Inter',
      heading_font: 'Inter',
      button_style: 'square',
      card_style: 'minimal',
      spacing: 'relaxed',
    },
  },

  // 37. Galaxy
  {
    id: 'galaxy',
    name: 'Galaxy',
    category: 'dark',
    description: 'Deep space with purple and blue nebula',
    preview: 'linear-gradient(135deg, #000000 0%, #312e81 50%, #1e1b4b 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Infinite Possibilities', subheading: 'Products as vast as the universe', showButton: true, buttonText: 'Explore' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'newsletter', type: 'newsletter', order: 3, heading: 'Join the Constellation', description: 'Get the latest drops.' },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'galaxy',
      page_bg_color: '#000000',
      card_bg_color: '#0f0e1a',
      text_color: '#e0e7ff',
      primary_button_bg: '#6366f1',
      primary_button_text: '#ffffff',
      primary_button_border: '#6366f1',
      primary_button_bg_hover: '#4f46e5',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#4f46e5',
      background_type: 'gradient',
      gradient_start: '#000000',
      gradient_end: '#1e1b4b',
      font_family: 'Inter',
      heading_font: 'Inter',
      button_style: 'rounded',
      card_style: 'standard',
    },
  },

  // 38. Copper
  {
    id: 'copper',
    name: 'Copper',
    category: 'luxury',
    description: 'Warm copper and bronze metallic luxury',
    preview: 'linear-gradient(135deg, #1c0f00 0%, #b45309 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'The Copper Standard', subheading: 'Warm metallic luxury for the refined', showButton: true, buttonText: 'Discover' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'The Collection', productsPerRow: '4', cardStyle: 'elevated' } },
      { id: 'testimonials', type: 'testimonials', order: 3, settings: { title: 'What Customers Say', testimonials: [{ name: 'Alex', text: 'Amazing products!', rating: 5 }, { name: 'Sam', text: 'Great quality.', rating: 5 }, { name: 'Jordan', text: 'Highly recommend!', rating: 5 }] } },
      { id: 'footer', type: 'footer', order: 4, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'copper',
      page_bg_color: '#1c0f00',
      card_bg_color: '#2a1800',
      text_color: '#fef3c7',
      primary_button_bg: '#b45309',
      primary_button_text: '#ffffff',
      primary_button_border: '#b45309',
      primary_button_bg_hover: '#92400e',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#92400e',
      background_type: 'solid',
      font_family: 'Playfair Display',
      heading_font: 'Playfair Display',
      button_style: 'pill',
      card_style: 'elevated',
    },
  },

  // 39. Hacker
  {
    id: 'hacker',
    name: 'Hacker',
    category: 'tech',
    description: 'Terminal green on black code aesthetic',
    preview: 'linear-gradient(135deg, #000000 0%, #052e16 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: '> ACCESS GRANTED', subheading: '// Products for those who know', showButton: true, buttonText: '> RUN' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: '> INVENTORY', productsPerRow: '4', cardStyle: 'standard' } },
      { id: 'footer', type: 'footer', order: 3, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'hacker',
      page_bg_color: '#000000',
      card_bg_color: '#001a00',
      text_color: '#00ff41',
      primary_button_bg: '#00ff41',
      primary_button_text: '#000000',
      primary_button_border: '#00ff41',
      primary_button_bg_hover: '#00cc33',
      primary_button_text_hover: '#000000',
      primary_button_border_hover: '#00cc33',
      background_type: 'solid',
      font_family: 'Roboto Mono',
      heading_font: 'Roboto Mono',
      button_style: 'square',
      card_style: 'standard',
    },
  },

  // 40. Cotton Candy
  {
    id: 'cotton-candy',
    name: 'Cotton Candy',
    category: 'light',
    description: 'Soft pastel pink and blue dreamy',
    preview: 'linear-gradient(135deg, #fce7f3 0%, #dbeafe 100%)',
    defaultSections: [
      { id: 'header', type: 'header', order: 0, store_name: '', show_nav: true },
      { id: 'hero', type: 'slideshow', order: 1, settings: { heading: 'Soft & Sweet', subheading: 'Dreamy products for dreamy people', showButton: true, buttonText: 'Shop Now' } },
      { id: 'products', type: 'product_grid', order: 2, settings: { title: 'Products', productsPerRow: '4', cardStyle: 'elevated' } },
      { id: 'testimonials', type: 'testimonials', order: 3, settings: { title: 'What Customers Say', testimonials: [{ name: 'Alex', text: 'Amazing products!', rating: 5 }, { name: 'Sam', text: 'Great quality.', rating: 5 }, { name: 'Jordan', text: 'Highly recommend!', rating: 5 }] } },
      { id: 'newsletter', type: 'newsletter', order: 4, heading: 'Sweet Deals Incoming', description: 'Get the latest drops.' },
      { id: 'footer', type: 'footer', order: 5, text: 'Powered by Vectabase', show_social: true },
    ],
    styleSettings: {
      template: 'cotton-candy',
      page_bg_color: '#fce7f3',
      card_bg_color: '#ffffff',
      text_color: '#1e3a5f',
      primary_button_bg: '#3b82f6',
      primary_button_text: '#ffffff',
      primary_button_border: '#3b82f6',
      primary_button_bg_hover: '#2563eb',
      primary_button_text_hover: '#ffffff',
      primary_button_border_hover: '#2563eb',
      background_type: 'solid',
      font_family: 'Poppins',
      heading_font: 'Poppins',
      button_style: 'pill',
      card_style: 'elevated',
    },
  },
];
