-- Event Horizon Seed Data
-- Generated: 2026-01-29T08:07:42.973Z
-- Auto-generated by pre-deploy script
-- This file is safe to commit to Git

BEGIN;

-- ============================================
-- USERS (3 records)
-- ============================================
INSERT INTO users (id, email, name, google_id, created_at, identity_id, provider) VALUES ('1', 'thecheesemanatyou@gmail.com', 'thecheese manatyou', '118142992181711626941', '2026-01-24T21:40:54.029Z', 'google:118142992181711626941', 'google') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, email, name, google_id, created_at, identity_id, provider) VALUES ('3', 'maxedwardcheetham@gmail.com', 'Phoenix Cheetah', '101801468049696456427', '2026-01-24T21:51:31.093Z', 'google:101801468049696456427', 'google') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, email, name, created_at, identity_id, provider) VALUES ('21', 'softwaredad4@gmail.com', 'software dad', '2026-01-26T21:08:46.224Z', 'google:114773045075293624419', 'google') ON CONFLICT (id) DO NOTHING;

-- ============================================
-- ORGANIZATIONS (4 records)
-- ============================================
INSERT INTO organizations (id, name, slug, owner_id, created_at) VALUES ('1', 'Default Org', 'default-org', '1', '2026-01-25T08:30:11.578Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name, slug, owner_id, created_at) VALUES ('2', 'Vectabase', 'vectabase', '1', '2026-01-25T08:41:36.187Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name, slug, created_at) VALUES ('5', 'Local Development', 'local-dev', '2026-01-25T17:08:50.754Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name, slug, owner_id, created_at) VALUES ('7', 'TestOrg', 'test-org', '1', '2026-01-25T19:29:55.359Z') ON CONFLICT (id) DO NOTHING;

-- ============================================
-- PROJECTS (7 records)
-- ============================================
INSERT INTO projects (id, name, slug, org_id, created_at) VALUES ('1', 'Main Project', 'main-project', '1', '2026-01-25T08:30:11.583Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO projects (id, name, slug, org_id, created_at) VALUES ('2', 'luzondev', 'luzondev', '2', '2026-01-25T08:51:12.232Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO projects (id, name, slug, org_id, created_at) VALUES ('3', 'Backup', 'backup', '1', '2026-01-25T08:56:36.786Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO projects (id, name, slug, org_id, created_at) VALUES ('4', 'Local Project', 'local-project', '5', '2026-01-25T17:09:46.260Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO projects (id, name, slug, org_id, created_at, encryption_salt) VALUES ('5', 'Web Test', 'web-test', '7', '2026-01-25T19:29:55.364Z', '7f4647069ca425e67e38039257f9ecad') ON CONFLICT (id) DO NOTHING;
INSERT INTO projects (id, name, slug, org_id, created_at) VALUES ('6', 'Vectabase', 'vectabase', '2', '2026-01-26T21:05:15.223Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO projects (id, name, slug, org_id, created_at, encryption_salt) VALUES ('7', 'Marketplace Vectabase', 'marketplace-vectabase', '2', '2026-01-26T21:05:30.852Z', '7dda241725edb69f59005caa53c637b1') ON CONFLICT (id) DO NOTHING;

-- ============================================
-- API_KEYS (5 records)
-- ============================================
INSERT INTO api_keys (id, project_id, key_hash, key_type, key_prefix, created_at, last_used_at) VALUES ('1', '4', '553ecf2b85c2f443cb651c1041c4a2764e05cbbc946e43b24707cc9abc5fdbb9', 'service_role', 'vb_secret_dev_12...', '2026-01-25T17:09:57.593Z', '2026-01-25T17:22:21.707Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO api_keys (id, project_id, key_hash, key_type, created_at) VALUES ('3', '1', '3c49d111db9258bc1dc282bd774da2b02390974bdb2a6b0dfb0bb76bf15f3cbb', 'anon', '2026-01-25T19:22:35.347Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO api_keys (id, project_id, key_hash, key_type, created_at, last_used_at) VALUES ('4', '5', '1e54820703418cf329b8864a79090256572ebad0fafef020d63655a788402205', 'anon', '2026-01-25T19:29:55.366Z', '2026-01-26T20:04:59.561Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO api_keys (id, project_id, key_hash, key_type, created_at, last_used_at) VALUES ('5', '5', 'd14c36bfed372f1295b4a8487f8f0e8a5b21e21881ce83a1d4c46fad41d132ff', 'service_role', '2026-01-26T19:55:27.551Z', '2026-01-26T20:10:09.783Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO api_keys (id, project_id, key_hash, key_type, created_at) VALUES ('6', '7', '1da5b938d6a3c5301ebeb877ba53c5efe5a64321c63d5452e82f24a5dea55e28', 'service_role', '2026-01-26T21:15:21.865Z') ON CONFLICT (id) DO NOTHING;

-- ============================================
-- EDGE_FUNCTIONS (6 records)
-- ============================================
INSERT INTO edge_functions (id, project_id, name, slug, trigger_type, created_at, updated_at) VALUES ('1', '5', 'Hello', 'hello', 'http', '2026-01-25T20:37:09.417Z', '2026-01-25T20:37:14.430Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO edge_functions (id, project_id, name, slug, trigger_type, created_at, updated_at) VALUES ('6', '5', 'Data Processor', 'data-processor', 'http', '2026-01-25T20:40:00.439Z', '2026-01-25T20:40:00.439Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO edge_functions (id, project_id, name, slug, trigger_type, created_at, updated_at) VALUES ('8', '5', 'User Analytics', 'user-analytics', 'http', '2026-01-25T20:46:28.509Z', '2026-01-25T20:46:51.046Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO edge_functions (id, project_id, name, slug, trigger_type, created_at, updated_at) VALUES ('10', '5', 'Complex Strategy', 'complex-strategy', 'http', '2026-01-25T20:53:07.679Z', '2026-01-25T20:59:07.945Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO edge_functions (id, project_id, name, slug, trigger_type, created_at, updated_at) VALUES ('12', '5', 'security-audit', 'security-audit', 'http', '2026-01-26T17:28:38.348Z', '2026-01-26T17:28:38.348Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO edge_functions (id, project_id, name, slug, trigger_type, created_at, updated_at) VALUES ('13', '5', 'cli-test-func', 'cli-test-func', 'http', '2026-01-26T20:02:58.184Z', '2026-01-26T20:04:59.701Z') ON CONFLICT (id) DO NOTHING;

COMMIT;

SELECT 'Seed data imported successfully!' AS status;
