#!/usr/bin/env node
/**
 * Pre-Deploy Script
 * Exports data from local Event Horizon PostgreSQL database
 * Run this BEFORE pushing to GitHub to prepare database for VPS deployment
 * 
 * Usage: node scripts/pre-deploy.js
 */

import pg from 'pg';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load Event Horizon env
const envPath = path.join(__dirname, '..', 'database', 'event-horizon-ui', '.env.local');
dotenv.config({ path: envPath });

const { Pool } = pg;

const SEED_FILE = path.join(__dirname, '..', 'database', 'event-horizon-ui', 'seed-data.sql');

async function generateSeedData() {
  console.log('🌱 Generating seed data from Event Horizon PostgreSQL...\n');
  
  const dbConfig = {
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '5432'),
    database: process.env.DB_NAME || 'postgres',
    user: process.env.DB_USER || 'postgres',
    password: process.env.DB_PASSWORD || 'postgres',
  };
  
  console.log(`📡 Connecting to PostgreSQL at ${dbConfig.host}:${dbConfig.port}/${dbConfig.database}...`);
  
  const pool = new Pool(dbConfig);
  
  try {
    const client = await pool.connect();
    console.log('✅ Connected to PostgreSQL!\n');
    
    let seedSql = `-- Event Horizon Seed Data
-- Generated: ${new Date().toISOString()}
-- Auto-generated by pre-deploy script
-- This file is safe to commit to Git

BEGIN;

`;
    
    // Check which tables exist
    const { rows: tables } = await client.query(`
      SELECT table_name FROM information_schema.tables 
      WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
      ORDER BY table_name
    `);
    
    const tableNames = tables.map(t => t.table_name);
    console.log(`📋 Found tables: ${tableNames.join(', ')}\n`);
    
    // Export users
    if (tableNames.includes('users')) {
      const { rows: users } = await client.query(`SELECT * FROM users ORDER BY created_at LIMIT 100`);
      if (users.length > 0) {
        seedSql += `-- ============================================\n-- USERS (${users.length} records)\n-- ============================================\n`;
        for (const user of users) {
          const cols = Object.keys(user).filter(k => user[k] !== null);
          const vals = cols.map(k => {
            const v = user[k];
            if (v === null) return 'NULL';
            if (typeof v === 'boolean') return v ? 'true' : 'false';
            if (v instanceof Date) return `'${v.toISOString()}'`;
            if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
            return `'${String(v).replace(/'/g, "''")}'`;
          });
          seedSql += `INSERT INTO users (${cols.join(', ')}) VALUES (${vals.join(', ')}) ON CONFLICT (id) DO NOTHING;\n`;
        }
        seedSql += '\n';
        console.log(`✅ Exported ${users.length} users`);
      }
    }
    
    // Export organizations
    if (tableNames.includes('organizations')) {
      const { rows } = await client.query(`SELECT * FROM organizations ORDER BY created_at LIMIT 100`);
      if (rows.length > 0) {
        seedSql += `-- ============================================\n-- ORGANIZATIONS (${rows.length} records)\n-- ============================================\n`;
        for (const row of rows) {
          const cols = Object.keys(row).filter(k => row[k] !== null);
          const vals = cols.map(k => {
            const v = row[k];
            if (v === null) return 'NULL';
            if (typeof v === 'boolean') return v ? 'true' : 'false';
            if (v instanceof Date) return `'${v.toISOString()}'`;
            if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
            return `'${String(v).replace(/'/g, "''")}'`;
          });
          seedSql += `INSERT INTO organizations (${cols.join(', ')}) VALUES (${vals.join(', ')}) ON CONFLICT (id) DO NOTHING;\n`;
        }
        seedSql += '\n';
        console.log(`✅ Exported ${rows.length} organizations`);
      }
    }
    
    // Export projects
    if (tableNames.includes('projects')) {
      const { rows } = await client.query(`SELECT * FROM projects ORDER BY created_at LIMIT 100`);
      if (rows.length > 0) {
        seedSql += `-- ============================================\n-- PROJECTS (${rows.length} records)\n-- ============================================\n`;
        for (const row of rows) {
          const cols = Object.keys(row).filter(k => row[k] !== null);
          const vals = cols.map(k => {
            const v = row[k];
            if (v === null) return 'NULL';
            if (typeof v === 'boolean') return v ? 'true' : 'false';
            if (v instanceof Date) return `'${v.toISOString()}'`;
            if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
            return `'${String(v).replace(/'/g, "''")}'`;
          });
          seedSql += `INSERT INTO projects (${cols.join(', ')}) VALUES (${vals.join(', ')}) ON CONFLICT (id) DO NOTHING;\n`;
        }
        seedSql += '\n';
        console.log(`✅ Exported ${rows.length} projects`);
      }
    }
    
    // Export api_keys
    if (tableNames.includes('api_keys')) {
      const { rows } = await client.query(`SELECT * FROM api_keys ORDER BY created_at LIMIT 100`);
      if (rows.length > 0) {
        seedSql += `-- ============================================\n-- API_KEYS (${rows.length} records)\n-- ============================================\n`;
        for (const row of rows) {
          const cols = Object.keys(row).filter(k => row[k] !== null);
          const vals = cols.map(k => {
            const v = row[k];
            if (v === null) return 'NULL';
            if (typeof v === 'boolean') return v ? 'true' : 'false';
            if (v instanceof Date) return `'${v.toISOString()}'`;
            if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
            return `'${String(v).replace(/'/g, "''")}'`;
          });
          seedSql += `INSERT INTO api_keys (${cols.join(', ')}) VALUES (${vals.join(', ')}) ON CONFLICT (id) DO NOTHING;\n`;
        }
        seedSql += '\n';
        console.log(`✅ Exported ${rows.length} api_keys`);
      }
    }
    
    // Export sessions
    if (tableNames.includes('sessions')) {
      const { rows } = await client.query(`SELECT * FROM sessions WHERE expires_at > NOW() ORDER BY created_at LIMIT 100`);
      if (rows.length > 0) {
        seedSql += `-- ============================================\n-- SESSIONS (${rows.length} active records)\n-- ============================================\n`;
        for (const row of rows) {
          const cols = Object.keys(row).filter(k => row[k] !== null);
          const vals = cols.map(k => {
            const v = row[k];
            if (v === null) return 'NULL';
            if (typeof v === 'boolean') return v ? 'true' : 'false';
            if (v instanceof Date) return `'${v.toISOString()}'`;
            if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
            return `'${String(v).replace(/'/g, "''")}'`;
          });
          seedSql += `INSERT INTO sessions (${cols.join(', ')}) VALUES (${vals.join(', ')}) ON CONFLICT (id) DO NOTHING;\n`;
        }
        seedSql += '\n';
        console.log(`✅ Exported ${rows.length} sessions`);
      }
    }
    
    // Export organization_members
    if (tableNames.includes('organization_members')) {
      const { rows } = await client.query(`SELECT * FROM organization_members ORDER BY created_at LIMIT 100`);
      if (rows.length > 0) {
        seedSql += `-- ============================================\n-- ORGANIZATION_MEMBERS (${rows.length} records)\n-- ============================================\n`;
        for (const row of rows) {
          const cols = Object.keys(row).filter(k => row[k] !== null);
          const vals = cols.map(k => {
            const v = row[k];
            if (v === null) return 'NULL';
            if (typeof v === 'boolean') return v ? 'true' : 'false';
            if (v instanceof Date) return `'${v.toISOString()}'`;
            if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
            return `'${String(v).replace(/'/g, "''")}'`;
          });
          seedSql += `INSERT INTO organization_members (${cols.join(', ')}) VALUES (${vals.join(', ')}) ON CONFLICT (id) DO NOTHING;\n`;
        }
        seedSql += '\n';
        console.log(`✅ Exported ${rows.length} organization_members`);
      }
    }
    
    // Export edge_functions
    if (tableNames.includes('edge_functions')) {
      const { rows } = await client.query(`SELECT * FROM edge_functions ORDER BY created_at LIMIT 100`);
      if (rows.length > 0) {
        seedSql += `-- ============================================\n-- EDGE_FUNCTIONS (${rows.length} records)\n-- ============================================\n`;
        for (const row of rows) {
          const cols = Object.keys(row).filter(k => row[k] !== null);
          const vals = cols.map(k => {
            const v = row[k];
            if (v === null) return 'NULL';
            if (typeof v === 'boolean') return v ? 'true' : 'false';
            if (v instanceof Date) return `'${v.toISOString()}'`;
            if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
            return `'${String(v).replace(/'/g, "''")}'`;
          });
          seedSql += `INSERT INTO edge_functions (${cols.join(', ')}) VALUES (${vals.join(', ')}) ON CONFLICT (id) DO NOTHING;\n`;
        }
        seedSql += '\n';
        console.log(`✅ Exported ${rows.length} edge_functions`);
      }
    }
    
    seedSql += `COMMIT;\n\nSELECT 'Seed data imported successfully!' AS status;\n`;
    
    client.release();
    
    // Write seed file
    await fs.writeFile(SEED_FILE, seedSql);
    
    // Get file stats
    const stats = await fs.stat(SEED_FILE);
    const sizeKB = (stats.size / 1024).toFixed(1);
    
    console.log('\n✅ Seed data generated successfully!');
    console.log(`   File: database/event-horizon-ui/seed-data.sql`);
    console.log(`   Size: ${sizeKB} KB`);
    
    return true;
    
  } catch (error) {
    console.error('❌ Database connection failed:', error.message);
    console.log('\n💡 Make sure Docker PostgreSQL is running:');
    console.log('   cd database && docker-compose up -d');
    return false;
  } finally {
    await pool.end();
  }
}

async function main() {
  console.log('═══════════════════════════════════════════');
  console.log('  VECTABASE PRE-DEPLOY PREPARATION');
  console.log('═══════════════════════════════════════════\n');
  
  const seedOk = await generateSeedData();
  
  console.log('\n═══════════════════════════════════════════');
  console.log('  NEXT STEPS');
  console.log('═══════════════════════════════════════════');
  
  if (seedOk) {
    console.log('\n✅ Ready to deploy! Run these commands:');
    console.log('   git add .');
    console.log('   git commit -m "Update database seed data"');
    console.log('   git push origin main');
    console.log('\n   Then on VPS run: ./deploy.sh');
  } else {
    console.log('\n⚠️ Could not export seed data.');
    console.log('   The schema.sql will still create tables on VPS.');
    console.log('   You may need to create test data manually.');
  }
}

main().catch(console.error);
